name: nmsc_todo
description: "Nipun's version of todo list"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  go_router: ^16.3.0
  google_sign_in: ^7.2.0
  http: ^1.5.0
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - .env
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito_ex_bold.ttf
          weight: 800
          style: normal
        - asset: assets/fonts/nunito_bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/nunito_semibold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/nunito_medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/nunito_regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/nunito_light.ttf
          weight: 300
          style: normal
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_black.ttf
          weight: 900
          style: normal
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/poppins_medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/poppins_thin.ttf
          weight: 100
          style: normal
